name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # 每日 UTC 00:00 產生一次
  workflow_dispatch: # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: d-ben-b
          outputs: |
            dist/snake.svg
      - name: Publish to branch 'output'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write
